version: 2

models:
  - name: stg_roads
    description: "Staging view for road network data."

    columns:
      - name: road_segment_id
        tests:
          - not_null
          - unique

      - name: road_class
        tests:
          - not_null

  - name: stg_gtfs
    description: "Staging view for transit stop metrics."

    columns:
      - name: stop_id
        tests:
          - not_null
          - unique

  - name: stg_weather
    description: "Staging view for hourly weather observations."

    columns:
      - name: timestamp
        tests:
          - not_null

  - name: stg_pois
    description: "Staging view for points of interest."

    columns:
      - name: osm_id
        tests:
          - not_null

  - name: stg_traffic
    description: "Staging view for traffic observations."

    columns:
      - name: traffic_location
        tests:
          - not_null

      - name: date
        tests:
          - not_null
